#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aiohttp
Version  : 3.4.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/09/01/22c9b713b195d071b73fdc2f977f8717497b0d30c41c0b4a9cd908b925ec/aiohttp-3.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/09/01/22c9b713b195d071b73fdc2f977f8717497b0d30c41c0b4a9cd908b925ec/aiohttp-3.4.0.tar.gz
Summary  : Async http client/server framework (asyncio)
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: aiohttp-python3
Requires: aiohttp-license
Requires: aiohttp-python
Requires: async-timeout
Requires: attrs
Requires: chardet
Requires: idna-ssl
Requires: multidict
Requires: yarl
BuildRequires : async-timeout
BuildRequires : attrs
BuildRequires : buildreq-distutils3
BuildRequires : chardet
BuildRequires : idna-ssl
BuildRequires : multidict
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : yarl

%description
Async http client/server framework
        ==================================

%package license
Summary: license components for the aiohttp package.
Group: Default

%description license
license components for the aiohttp package.


%package python
Summary: python components for the aiohttp package.
Group: Default
Requires: aiohttp-python3

%description python
python components for the aiohttp package.


%package python3
Summary: python3 components for the aiohttp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the aiohttp package.


%prep
%setup -q -n aiohttp-3.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535212892
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/aiohttp
cp LICENSE.txt %{buildroot}/usr/share/doc/aiohttp/LICENSE.txt
cp vendor/http-parser/LICENSE-MIT %{buildroot}/usr/share/doc/aiohttp/vendor_http-parser_LICENSE-MIT
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/aiohttp/LICENSE.txt
/usr/share/doc/aiohttp/vendor_http-parser_LICENSE-MIT

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
